auction_site/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'site#home'
  get '/users', to: 'users#index'
  get '/users/new', to: 'users#new'
  get '/users/:id', to: 'users#show'

  post '/users', to: 'users#create'

  delete '/users/:id/delete', to: 'users#destroy'

  get '/products', to: 'products#index', as: :user_products
  get '/users/:user_id/products/new', to: 'products#new'
  get '/users/:user_id/products/show', to: 'products#show'
  post '/users/:user_id/products', to: 'products#create'

end

auction_site/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

auction_site/app/models/bid.rb
class Bid < ApplicationRecord
  belongs_to :user
  belongs_to :product

  def expired_time
    
  end

end

auction_site/app/models/product.rb
class Product < ApplicationRecord
	belongs_to :user
	has_many :bids
end

auction_site/app/models/user.rb
class User < ApplicationRecord
	has_many :products
	has_many :bids
end

auction_site/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

auction_site/app/controllers/bids_controller.rb
class BidsController < ApplicationController

  def create
    user = User.find_by(email: params[:email])
    @product = Product.find_by(params[:product_id])
    @bids = @product.bids
    @my_bid = Bid.new(amount: params[:amount], product_id: params[:product_id])


    if condition

    end
  end
end

auction_site/app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def index
		@products = Product.all
	end

	def show
		@product = Product.find(params[:id])

	end

	def new
		@user = User.find(params[:user_id])
		@products = @user.products.new
	end

	def create
		@product = @user.products.new(product_params)
		if @product.save
			redirect_to user_product_path(@user.id)
		else
			render "new"
		end

	end

	def destroy
		Product.find(params[:id]).destroy
		redirect_to user
	end

end

auction_site/app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
    
  end
end

auction_site/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

	def show
		@user = User.find_by(id: params[:id])
		@products = @user.products
	end

	def new
		@user = User.new
	end

	def create
		@user = User.new(
		:name => params[:user][:name],
		:email => params[:user][:email])
		
		if @user.save
			redirect_to '/users/'
		else
			render "error"
		end	
	end

	def destroy
    	User.find(params[:id]).destroy
		redirect_to "/users"
  	end

end

auction_site/app/helpers/application_helper.rb
module ApplicationHelper
end

auction_site/app/helpers/bids_helper.rb
module BidsHelper
end

auction_site/app/helpers/product_helper.rb
module ProductHelper
end

auction_site/app/helpers/products_helper.rb
module ProductsHelper
end

auction_site/app/helpers/site_helper.rb
module SiteHelper
end

auction_site/app/helpers/user_helper.rb
module UserHelper
end

auction_site/app/helpers/users_helper.rb
module UsersHelper
end

auction_site/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuctionSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

auction_site/app/views/products/index.html.erb
<h1> Products </h1>

<ul>
	
	<% @products.each do |product| %>

	<li>
		<%= product.title%> -
		<%= product.description%> -
		<%= product.deadline%></a>
	</li>

	<% end %>

</ul>

auction_site/app/views/products/new.html.erb
<h1> NEW PRODUCT </h1>

<%= form_for [@users, @products] do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>

	<%= f.label :description %>
	<%= f.text_field :description%>

	<%= f.label :deadline %>
	<%= f.date_field :deadline%>

	<%= f.label :minimum_bid %>
	<%= f.text_field :minimum_bid%>

	<%= f.submit  "Save"%>
<% end %>

auction_site/app/views/products/show.html.erb
<h1><%= @product.title%></h1>

<ul>
	<li><%= @product.description%></li>
	<li><%= @product.deadline%></li>
	<li><%= @product.user.name%></li>

</ul>

auction_site/app/views/site/home.html.erb
<h2>AUCTION SITE</h2>


<%= image_tag 'bfSin.gif', alt: 'alt text', class: 'image' %>

<br>
<p>Ironhack powered</p>

auction_site/app/views/users/index.html.erb
<h1>Users</h1>

<ul>

	<% @users.each do |a| %>

		<li>
			<a href="/users/<%= a.id%>">
			<%= a.name %>
			</a>
		</li>
		
	<% end %>

</ul>
<%= link_to "Sign up", "/users/new" %>

auction_site/app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for @user do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>

	<%= f.label :email %>
	<%= f.email_field :email %>

	<%= f.button %>
<% end %>

auction_site/app/views/users/show.html.erb
<p>Name: <%= @user.name %></p>

<p>Description: <%= @user.email%></p>

<%= link_to "Products", user_products_path(@user) %>
<br>
<br>
<%= link_to "Delete", "/users/#{@user.id.to_s}/delete" , method: :delete, data: { confirm: "Are you sure?"} %>
<br>
<br>
<%= link_to "Back to users", "/users" %>